#!/usr/bin/env bash
# Used in the installer tool to install the desired path to your system.
#
# Uses the tool.toml file to get the tool file name.
#
# Local installs go to:
#   ~/.local/bin
#   ~/.local/lib
#
# Global installs go to:
#   /usr/bin
#   /usr/lib

## SOURCE GUARD bashlib_install ----------------------------------------------------------
if [[ -v installer_cli_install_sourced ]]; then
    return 0
fi
installer_cli_install_sourced=1
## ---------------------------------------------------------------------------------------

## SECTION USED TO GET CORRECT SOURCE PATH DO NOT REMOVE.
# Name of the main tool
installer_tool_name="installer"
installer_cli_install_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
installer_tool_lib_dir=""

# Resolve install/dev paths
if [[ "${installer_cli_install_dir}" == "${HOME}/.local/libexec/${installer_tool_name}" ]]; then
    [[ -d "${HOME}/.local/lib/${installer_tool_name}" ]] && installer_tool_lib_dir="${HOME}/.local/lib/${installer_tool_name}"
elif [[ "${installer_cli_install_dir}" == "/usr/libexec/${installer_tool_name}" ]]; then
    [[ -d "/usr/lib/${installer_tool_name}" ]] && installer_tool_lib_dir="/usr/lib/${installer_tool_name}"
else
    [[ -d "${installer_cli_install_dir}/../lib" ]] && installer_tool_lib_dir="${installer_cli_install_dir}/../lib"
fi

source "${installer_tool_lib_dir}/bashlib_install.bash"
## End of  SOURCE GUARD



# Set to false by default so tools go to local install.
INSTALL_GLOBAL=false
# path where the tool will be installed. (/usr, ~/.local)
# Set based on the INSTALL_GLOBAL flag.
INSTALL_LOCATION=""
TOOL_PATH=""				# Path to the tools project.
REPO=false

_install_usage() {
 a   cat <<EOF
Usage:
  installer install [options] <path>

Options:
  -g, --global			Install globally
  --repo			installs from a repo instead.
  --help			Show this help message

Behavior:
  Expects a project layout like:
    <project-root>/<tool-name>
    <project-root>/tool.toml
    <project-root>/lib/

  Installs:
    <tool-name> -> <prefix>/bin/<tool-name>
    lib/        -> <prefix>/lib/<tool-name>/
    tool.toml   -> <prefix>/lib/<tool-name>/tool.toml

Examples:
  installer install ./installer
  installer install --global ./installer
  installer install --repo "https://github.com/JMinyard1335/Bash-Installer"
  installer install --global --repo "https://github.com/JMinyard1335/Bash-Installer"
EOF
}

## Logging functions ------------------------------------------------------------------------
_install_log() {
    printf "${CYAN}[install]:${RESET} %s\n" "$*"
}

_install_error() {
    printf "${RED}[install-Err]:${RESET} %s\n" "$*" >&2
}


_install_warn() {
    printf "${YELLOW}[install-Warn]:${RESET} %s\n" "$*" >&2
}

_install_success() {
    printf "${GREEN}[install-Ok]:${RESET} %s\n" "$*"
}

## ------------------------------------------------------------------------------------------
# _install_parse_args <args...>
# Parses:
#   -g | --global
#   --help
#   <path>
_install_parse_args() {
    TOOL_PATH=""
    INSTALL_GLOBAL=false
    REPO=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help)
                _install_usage
                return 2
                ;;
            -g|--global)
                INSTALL_GLOBAL=true
                shift
                ;;
            --repo)
                REPO=true
                shift
                ;;
            --)
                shift
                break
                ;;
            -*)
                _install_error "Unknown option: $1"
                _install_usage
                return 1
                ;;
            *)
                if [[ -n "$TOOL_PATH" ]]; then
                    _install_error "Too many arguments: $1"
                    _install_usage
                    return 1
                fi
                TOOL_PATH="$1"
                shift
                ;;
        esac
    done

    while [[ $# -gt 0 ]]; do
        if [[ -n "$TOOL_PATH" ]]; then
            _install_error "Too many arguments: $1"
            _install_usage
            return 1
        fi
        TOOL_PATH="$1"
        shift
    done

    if [[ -z "$TOOL_PATH" ]]; then
        if [[ "$REPO" == true ]]; then
            _install_error "Missing repository URL."
        else
            _install_error "Missing install path."
        fi
        _install_usage
        return 1
    fi

    return 0
}

# _install_get_dir() <global-flag>
# if the global flag is true the install
# location is set to /usr else ~/.local
_install_get_dir() {
    local global="$1"
    if [[ "$global" == true ]]; then
	INSTALL_LOCATION="/usr"
    else
	INSTALL_LOCATION="$HOME/.local"
    fi
}


# install_cmd
# the front facing api of this script.
install_cmd() {
    local tool=""
    local parse_status=0

    _install_parse_args "$@"
    parse_status=$?

    case "$parse_status" in
        0) ;;
        1) return 1 ;;
        2) return 0 ;;
        *) return 1 ;;
    esac

    _install_get_dir "$INSTALL_GLOBAL"
    _install_log "Installing to ${MAGENTA}$INSTALL_LOCATION${RESET}"

    _install_check_dir "$INSTALL_LOCATION" || return 1

    if [[ "$REPO" == true ]]; then
        _install_log "Installing from repo ${MAGENTA}$TOOL_PATH${RESET}"
        bashlib_install_from repo "$TOOL_PATH" "$INSTALL_LOCATION" 0 || return 1
    else
        if [[ ! -d "$TOOL_PATH" ]]; then
            _install_error "Install path is not a directory: $TOOL_PATH"
            return 1
        fi
	
        _install_log "Installing $tool..."
        bashlib_install_from_source "$TOOL_PATH" "$INSTALL_LOCATION" 0 || return 1
    fi

    _install_success "Install complete."
    echo ""
    _install_warn 'READ THE FOLLOWING:'
    _install_warn 'If installed locally:'
    _install_warn '  add '"${MAGENTA}"'$HOME/.local/bin'"${RESET}"' to your PATH'
    echo ""
    _install_log 'add '"${MAGENTA}"'export PATH="$PATH:$HOME/.local/bin"'"${RESET}"' to your .bashrc file.'
    _install_log '.bashrc can be found at: '"${MAGENTA}"'~/.bashrc'"${RESET}"
}
